DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE PRODUCTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ean VARCHAR(13) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    provider VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL
);

CREATE TABLE USERS (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(255) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL,
   enabled BOOLEAN NOT NULL
);
